info:
  app:
    name: trade-order-gateway
    env: local
    ver: v0.0.1

server:
  port: 8088

spring:
  redis:
    host: campus-dev.redis.ksyun.com
    port: 26356
    password: TkSbRi%xQtFkEX98BQR3yQ==
    database: 3


#actions: http://localhost:8089,http://localhost:8089
actions: http://campus.query1.ksyun.com:8089,http://campus.query2.ksyun.com:8089
meta: http://campus.meta.ksyun.com:8090
